export const MovementConfig = {
  fixedTimeStep: 1 / 60,
  capsuleRadius: 0.35,
  capsuleHeight: 1.8,
  eyeHeight: 1.62,
  stepHeight: 0.35,
  slopeLimitDegrees: 44,
  gravity: 22,
  jumpImpulse: 6.5,
  maxGroundSpeed: 5.5,
  maxAirSpeed: 2.5,
  noclipSpeed: 7.5,
  groundAcceleration: 55,
  airAcceleration: 8,
  friction: 12,
  groundProbeDistance: 0.08,
  groundLiftDistance: 0.04,
  groundSnapEpsilon: 0.003,
  groundContactSlop: 0.006,
  traceEpsilon: 0.001,
  nonJumpVelocity: 2.7,
  maxClipBumps: 4,
  maxClipPlanes: 5,
  headbobEnabled: true,
  headbobMinSpeed: 0.2,
  headbobFrequency: 1.85,
  headbobVerticalAmplitude: 0.035,
  headbobLateralAmplitude: 0.018,
  headbobSmoothing: 12,
}
